name: Build amqp

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint-ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
